name: Deploy

on:
  push:
    branches:
      - *

jobs:
  code-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

  automated-tests:
    runs-on: ubuntu-latest
    needs: code-setup
    steps:
      - name: Run unit tests
        run: yarn test
        continue-on-error: false

      - name: Run ESLint
        run: yarn run lint
        continue-on-error: false

  deploy:
    runs-on: ubuntu-latest
    needs: automated-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !failure()

    steps:
      - name: Build
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
