name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  automated-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare the code
        uses: ./.github/actions/code-prep

      - name: Run unit tests
        run: yarn test
        continue-on-error: false

      - name: Run ESLint
        run: yarn run lint
        continue-on-error: false

  deploy:
    if: github.event_name == 'push' && github.ref_name == 'master' && !failure()
    runs-on: ubuntu-latest
    needs: automated-tests
    steps:
      - uses: actions/checkout@v4
      - name: Prepare the code
        uses: ./.github/actions/code-prep

      - name: Build
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
