name: Deploy

on:
  push:
    branches:
      - '*'

env:
  BRANCH_NAME: ${{ github.ref }##*/}

jobs:
  automated-tests:
    runs-on: ubuntu-latest
    needs: code-setup
    steps:
      - uses: ./build.yaml

      - name: Run unit tests
        run: yarn test
        continue-on-error: false

      - name: Run ESLint
        run: yarn run lint
        continue-on-error: false

  deploy:
    runs-on: ubuntu-latest
    needs: automated-tests
    if: github.event_name == 'push' && $BRANCH_NAME == 'master' && !failure()

    steps:
      - uses: ./build.yaml

      - name: Build
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
